### ISSUE TITLE
Incorrect titles and videos in 'Form Testing' section

### ISSUE THREAD

**Issue by vasilii-kovalev** [kentcdodds/testing-react-apps#34]
How the playlist looks like:
![image](https://user-images.githubusercontent.com/10310491/97170573-f8b6d200-179c-11eb-82ed-7156bb3fc595.png)

How the markdown section titles look like:
![image](https://user-images.githubusercontent.com/10310491/97171039-cd80b280-179d-11eb-9340-126696d61bc1.png)
![image](https://user-images.githubusercontent.com/10310491/97170699-2e5bbb00-179d-11eb-8d66-7cf716a4c1ed.png)
![image](https://user-images.githubusercontent.com/10310491/97170730-39aee680-179d-11eb-82c5-4d1fd6aed75f.png)

"Abstract Variables" video is absolutely the same as "Jest Mock Functions" with different placeholders, "Jest Mock" shouldn't be `Solution` since it is in `Extra Credit`-s, the videos order is incorrect.

So, something is wrong with this exercise from videos and/or docs perspective.
@kentcdodds

**Comment by kentcdodds** [comment]
cc @dealingwith :)

**Comment by kentcdodds** [comment]
Reported 👍
