### ISSUE TITLE
[Exercise - 6] Have a different test for checking spinner

### ISSUE THREAD

**Issue by respel** [kentcdodds/testing-react-apps#56]
Hi
I was working through this workshop and stumbled on exercise 6. 

Checking the position, as well as the spinner in the same test, is leading it to be convoluted. Splitting it into two simplifies a lot of stuff.

My suggestion is to have a different test for checking the "loading" state.

**Comment by kentcdodds** [comment]
@respel,

Testing approaches (like all software) is more subjective than we sometimes think. I disagree with you, but I don't think that your suggestion is problematic at all.

In any case, we'll leave it as it is. Thanks anyway!
