### ISSUE TITLE
Exercice 6: use waitForElementToBeRemoved instead of manual await

### ISSUE THREAD

**Issue by ValentinH** [kentcdodds/testing-react-apps#58]
This is a follow-up after a discussion on Discord.

In exercice 6, we need to use `act()`. When doing the exercice, I used `waitForElementToBeRemoved()`. Isn't this better than manually awaiting for the promise? Maybe, waiting for the promise in this lesson was for introducing when/how to use `act()` ?
![image](https://user-images.githubusercontent.com/2678610/103521418-019ce180-4e79-11eb-9c60-f3d6bd148c3a.png)

If you change it, it might also impact the "extra credit 1" as there is no promise there and `act` is used.

**Comment by kentcdodds** [comment]
I'll make sure to do this in the updated version 👍

**Comment by kentcdodds** [comment]
This update has happened in the `next` branch 👍
