### ISSUE TITLE
JS file extension references in markdown instructions

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/testing-react-apps#69]
Working with instructions in the `next` TS branch, I notice a few places in 05.md, 06.md, and 07.md which mention JS file extensions:
![search for \.js\b](https://user-images.githubusercontent.com/1087670/139541153-022cf29b-0305-4f02-a4cf-7ed6028a7efd.png)

The `test/server-handlers.js` mentioned in 05.md extra credit 1 is an instruction for importing - to my surprise the import works even with `.js` extension even though only `.ts` file exists in that directory 🤷‍♂️ so maybe no action needed, up to you.

**Comment by Aprillion** [comment]
Actually, VS Code pretends that the `.js` file can be imported and click-through works, Jest itself does not have any black magic to resolve `.js` file extension when only a `.ts` file exists => the files should be either called `.ts` in the `next` branch or we could use another import black magic and don't use any file extension, so the same `.md` files can be used in both `main` and `next` branches.

**Comment by kentcdodds** [comment]
Thanks! I'd prefer to just use `.ts` in the `next` branch. Updated 👍
