### ISSUE TITLE
Link broken in exercise 6 MD file

### ISSUE THREAD

**Issue by forbesd7** [kentcdodds/testing-react-apps#80]
The link to 'Advanced React Hooks workshop' is currently broken (404 on your site).  Probably wanting to link to this? https://github.com/kentcdodds/advanced-react-hooks 
<img width="580" alt="Screen Shot 2022-04-05 at 12 00 59" src="https://user-images.githubusercontent.com/54018183/161670562-8754a6e9-d5de-46e8-b44d-f5a1cd5b709f.png">

**Comment by kentcdodds** [comment]
Thanks for letting me know! I've updated that URL to redirect to the right spot now (currently deploying). Cheers :)
