### ISSUE TITLE
Overrides don't work the same with test-data-bot as previous extra credit

### ISSUE THREAD

**Issue by fitzage** [kentcdodds/testing-react-apps#88]
In exercise 4 extra credit 3, we allowed overrides for our object factory.

In extra credit 4, no mention is made of the fact that the overrides have to be passed differently. The video makes it sound like you can just do it in the same way, but that doesn't work.

In extra credit 3, we can call `buildLoginForm({username: 'chucknorris'})`, but in extra credit 4 it needs to be `buildLoginForm({overrides: {username: 'test'}})`.

This threw me for a loop until I looked back at the docs for test-data-bot. I feel like this should have been called out somewhere.

**Comment by kentcdodds** [comment]
Good point! Would you be willing to add a note to the markdown file to help people know about the change?
