### ISSUE TITLE
Exercise 01 is updated to React 18 but lacks instructions

### ISSUE THREAD

**Issue by Eugenijus** [kentcdodds/testing-react-apps#90]
Exercise 01.js is updated to React 18. However 01.md lacks the instructions for new to testing on how to create `root` element, how to use `createRoot()` and  does not mention `act()` which is used in the solution (with the exception to the link about configuration).

The video on epicreact.dev uses previous React version and instructions there are outdated.

**Comment by kentcdodds** [comment]
Ah! I'm not sure how I missed that! Sorry about that. Would you like to make a pull request to fix that?

**Comment by ACPK** [comment]
@Eugenijus Thanks for posting. @kentcdodds A PR would not update the solution video.
