### ISSUE TITLE
Exercise 03 - Trigger click event using userEvent doesn't work

### ISSUE THREAD

**Issue by Boamorte8** [kentcdodds/testing-react-apps#91]
After I check the video of the solution for the extra credit for exercise 03, I found that the unit tests fail. After a little research on StackOverflow I found this [answer](https://stackoverflow.com/questions/73232927/react-testing-userevent-click-does-not-work) and I checked the code and 
![image](https://user-images.githubusercontent.com/7391111/207704422-d155b36d-9f44-430b-ab99-ec80743faec9.png)

After I compare it with fireEvent, I can say that the problem is that userEvent.click returns a promise. The click event is not executed. You need to wait until the promise is executed before assert 

After you add await the test works well and passes it

**Comment by kentcdodds** [comment]
Thanks for bringing this up. I guess I neglected to add a note about this in the extra credit description. I've fixed that. Thanks!
