### ISSUE TITLE
Need to downgrade `npm` in order to setup the project

### ISSUE THREAD

**Issue by Diveafall** [kentcdodds/testing-react-apps#92]
I get this error when setting up the project.
```
This computer has node@v19.2.0 installed, but node@14 || 16 || 18 is required. Please update node: https://nodejs.org
```
I'm reluctant to downgrade the version. Is it really necessary?

**Comment by kentcdodds** [comment]
I just updated the version requirements for this workshop. Thanks for letting me know.
