### ISSUE TITLE
Excercise 05 is using msw 1.0 (rest). I think we should update to 2.0 (http)

### ISSUE THREAD

**Issue by ajaralampidis** [kentcdodds/testing-react-apps#97]
I am following the tutorials so I don't know if this impacts other exercises.

**Why should we update ?**
- if you use msw documentation, it uses `http` API instead of `rest`. Changes in the API are not big, but this might cause some trouble for someone (it kind of did to me because I was searching in the docs using "rest" as a keyword and I was encountering the "HTTP" API instead).
- to keep the course up to date

**Problems with the update:**
- Changing rest with HTTP directly might require a video update, not only a PR in the repo

I suggest, until the video update, to leave a comment and/or an extra credit telling students about msw update: https://mswjs.io/docs/migrations/1.x-to-2.x
https://mswjs.io/blog/introducing-msw-2.0

I can open a PR if this sounds ok.

**Comment by kentcdodds** [comment]
Thanks for the issue! I'm in the middle of updating all of Epic React and I will certainly be using the latest version of all dependencies (including MSW) in the process. Stay tuned :) Thanks!
